= Omar's PostMark

PostMark is old and disgusting. OMark is a clean rewrite from scratch,
developed during research for http://arrakis.cs.washington.edu/[Arrakis].

Compared to Postmark, OMark:

- Supports multi-core benchmarking
- Is written in modern C99
- Is highly configurable

Like PostMark, OMark simulates a ``realistic'' server filesystem workload
(specifically, a mail server): lots of small, short-lived files which are
created, deleted, read from, and appended to. The benchmark models this by
creating an initial pool of files of random size and contents and then carrying
out these operations at random.

== Benchmark Configuration
OMark is configured with a configuration file which is specified with the `-c`
flag. The format is a simple series of `key value` lines, where the valid keys
are:

- `block-size` (integer): size of I/O operations
- `block-aligned` (boolean): should all files and I/O be aligned to the block size?
- `initial-files` (integer): number of files to create before starting the benchmark
- `min-file-size` (integer): minimum size of file when it is initially created
- `max-file-size` (integer): maximum size of file when it is initially created
- `min-write-size` (integer): minimum size of write operation
- `max-write-size` (integer): maximum size of write operation
- `io-dir-ratio` (real): ratio of I/O operations (reads/writes) to directory operations (creates/deletes)
- `read-write-ratio` (real): ratio of reads to writes
- `create-delete-ratio` (real): ratio of creates to deletes
- `max-operations` (integer): maximum number of operations to run (0 means no limit)
- `time-limit` (integer): maximum number of seconds to run (0 means no limit)

All parameters are optional and have reasonable defaults. Here is an example of
a benchmark that only does reads and writes (no creates or deletes), 60% of
which are reads:

----
block-aligned false
io-dir-ratio 1.0
read-write-ratio 0.6
----

Notice that only properties of the benchmark itself are configured in the
configuration file. Properties of a particular run (like how many processes to
run or which directory to run in) are specified with command line flags instead.
