= Omar's PostMark
Omar Sandoval <osandov@osandov.com>

PostMark is old and disgusting. OMark is a clean rewrite from scratch,
developed during research for http://arrakis.cs.washington.edu/[Arrakis].

Compared to Postmark, OMark:

- Supports multi-core benchmarking
- Is written in modern C99
- Is configurable with JSON

Like PostMark, OMark simulates a ``realistic'' server filesystem workload
(specifically, a mail server): lots of small, short-lived files which are
created, deleted, read from, and appended to. The benchmark models this by
creating an initial pool of files of random size and contents and then carrying
out these operations at random.

== Usage
OMark is configured with a JSON configuration file which is specified with the
`-c` flag. This can be used to specify:

- The size of the initial file set
- The read-to-write operation create-to-delete operation ratios
- A maximum number of operations or time limit

[source,json]
----
{
	"initial-files": 1000,
	"read-write-ratio": 0.75,
	"create-delete-ratio": 0.8,
	"max-operations": 10000,
	"time-limit": 10
}
----

The configuration file is meant to specify properties of the benchmark itself as
opposed to a particular run. For that reason, properties like the number of CPU
cores and the directory to run in are specified with command line flags:

- `-c CONFIG`: JSON configuration file to use
- `-C DIR`: directory to run in
- `-s CPUSET`: CPU set to run on, specified as comma-separated list of integers
  defaults to just CPU 0
